services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    # The command tells it where the files are and how to connect to Postgres
    command:
      - -path=/migrations/
      - -database=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
