// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Paper struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
}

type PaperChunk struct {
	ID         int32
	PaperID    pgtype.Int4
	Content    string
	ChunkIndex pgtype.Int4
	Embedding  pgvector.Vector
}
