// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createPaper = `-- name: CreatePaper :one
INSERT INTO papers (title)
VALUES ($1)
RETURNING id, title, created_at
`

func (q *Queries) CreatePaper(ctx context.Context, title string) (Paper, error) {
	row := q.db.QueryRow(ctx, createPaper, title)
	var i Paper
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const createPaperChunk = `-- name: CreatePaperChunk :one
INSERT INTO paper_chunks (paper_id, content, chunk_index, embedding)
VALUES ($1, $2, $3, $4)
RETURNING id, paper_id, content, chunk_index, embedding
`

type CreatePaperChunkParams struct {
	PaperID    pgtype.Int4
	Content    string
	ChunkIndex pgtype.Int4
	Embedding  pgvector.Vector
}

func (q *Queries) CreatePaperChunk(ctx context.Context, arg CreatePaperChunkParams) (PaperChunk, error) {
	row := q.db.QueryRow(ctx, createPaperChunk,
		arg.PaperID,
		arg.Content,
		arg.ChunkIndex,
		arg.Embedding,
	)
	var i PaperChunk
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Content,
		&i.ChunkIndex,
		&i.Embedding,
	)
	return i, err
}

const deletePaper = `-- name: DeletePaper :exec
DELETE FROM papers
WHERE id = $1
`

func (q *Queries) DeletePaper(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePaper, id)
	return err
}

const getPaperByID = `-- name: GetPaperByID :one
SELECT id, title, created_at FROM papers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaperByID(ctx context.Context, id int32) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaperByID, id)
	var i Paper
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const listChunksByPaper = `-- name: ListChunksByPaper :many
SELECT id, paper_id, content, chunk_index, embedding FROM paper_chunks
WHERE paper_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListChunksByPaper(ctx context.Context, paperID pgtype.Int4) ([]PaperChunk, error) {
	rows, err := q.db.Query(ctx, listChunksByPaper, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperChunk
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.Content,
			&i.ChunkIndex,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarChunks = `-- name: SearchSimilarChunks :many
SELECT 
    pc.id, 
    pc.content, 
    pc.paper_id,
    p.title as paper_title,
    1 - (pc.embedding <=> $1) AS similarity
FROM paper_chunks pc
JOIN papers p ON pc.paper_id = p.id
ORDER BY pc.embedding <=> $1
LIMIT $2
`

type SearchSimilarChunksParams struct {
	Embedding pgvector.Vector
	Limit     int32
}

type SearchSimilarChunksRow struct {
	ID         int32
	Content    string
	PaperID    pgtype.Int4
	PaperTitle string
	Similarity float64
}

// We use the <=> operator for cosine distance (smaller is better)
func (q *Queries) SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarChunks, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSimilarChunksRow
	for rows.Next() {
		var i SearchSimilarChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.PaperID,
			&i.PaperTitle,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
